### ISSUE TITLE
Question regarding the release strategy for Koin different libraries

### ISSUE THREAD

**Issue by bahaa-kallas** [InsertKoinIO/koin#1687]
**Issue Description**

In our version catalog we do use the same version reference for these three `koin` dependencies 

```toml
koin="3.5.1"

koin-ktor = { module = "io.insert-koin:koin-ktor" , version.ref = "koin"  }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j" , version.ref = "koin"  }
koin-test = { module = "io.insert-koin:koin-test" , version.ref = "koin"  }
```

Recently our dependency bot updated the version reference to `3.5.1` which caused an issue when fetching `koin-test` as `koin-test` doesn't have 3.5.1 released artifact and its latest artifact was 3.5.0 

**Expected behavior**
Not entirely sure wether those 3 deps was supposed to have the same versioning or not. But it seems for the last 2 years (The lifetime of our product) those 3 deps used to have the exact same versioning. 
I would really appreciate if someone can confirm the previous assumption so I can adjust our version catalogs accordingly.
